### ISSUE TITLE
mbr structures error on image generation

### ISSUE THREAD

**Issue by sangshuduo** [uCRDev/Bubblegum96-Snappy#2]
$ sudo /snap/bin/ubuntu-image --channel stable --image-size 2G --extra-snaps bubblegum96-gadget_16.04-1.1_arm64.snap --extra-snaps bubblegum96-kernel_3.10.0_arm64.snap -o bubblegum96.img bubblegum96.model
Fetching core
Copying "bubblegum96-kernel_3.10.0_arm64.snap" (bubblegum96-kernel)
Copying "bubblegum96-gadget_16.04-1.1_arm64.snap" (bubblegum96-gadget)
bubblegum96-gadget already prepared, skipping
bubblegum96-kernel already prepared, skipping
gadget.yaml parse error: mbr structures cannot be larger than 446 bytes.
Use --debug for more information

**Comment by sangshuduo** [comment]
$ sudo /snap/bin/ubuntu-image --channel stable --image-size 2G --extra-snaps bubblegum96-gadget_16.04-1.1_arm64.snap --extra-snaps bubblegum96-kernel_3.10.0_arm64.snap -o bubblegum96.img bubblegum96.model --debug
[sudo] password for shuduo: 
DEBUG:ubuntu-image:-> [ 0] make_temporary_directories
DEBUG:ubuntu-image:-> [ 1] prepare_image
Fetching core
Copying "bubblegum96-kernel_3.10.0_arm64.snap" (bubblegum96-kernel)
Copying "bubblegum96-gadget_16.04-1.1_arm64.snap" (bubblegum96-gadget)
bubblegum96-gadget already prepared, skipping
bubblegum96-kernel already prepared, skipping
DEBUG:ubuntu-image:-> [ 2] load_gadget_yaml
ERROR:ubuntu-image:uncaught exception in state machine step: [2] load_gadget_yaml
Traceback (most recent call last):
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/state.py", line 73, in __next__
    step()
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/builder.py", line 133, in load_gadget_yaml
    self.gadget = parse_yaml(fp)
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/parser.py", line 413, in parse
    'mbr structures cannot be larger than 446 bytes.')
ubuntu_image.parser.GadgetSpecificationError: mbr structures cannot be larger than 446 bytes.
ERROR:ubuntu-image:gadget.yaml parse error
Traceback (most recent call last):
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/__main__.py", line 158, in main
    list(state_machine)
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/state.py", line 73, in __next__
    step()
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/builder.py", line 133, in load_gadget_yaml
    self.gadget = parse_yaml(fp)
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/parser.py", line 413, in parse
    'mbr structures cannot be larger than 446 bytes.')
ubuntu_image.parser.GadgetSpecificationError: mbr structures cannot be larger than 446 bytes.


$ snap list
Name                 Version     Rev  Developer   Notes
ubuntu-image         0.12+real1  44   canonical   devmode

**Comment by alephman** [comment]
ubuntu-image （0.12）fixed a bug, which may cause the issue, the detailed information is here (https://bugs.launchpad.net/ubuntu-image/+bug/1630769).   This issue is fixed by commit 3d33531.
